on:
  pull_request:
    branches:
      - master
jobs:
  test_master_merge:
    name: Test master merge
    runs-on: ubuntu-latest
    steps:
      - name: step01
          if: github.event.action == 'merged'
          run: yarn env
