name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - test_actions

jobs:
  test_master_merge:
    name: Test master merge
    runs-on: ubuntu-latest
    steps:
      - name: Just echo some shit
        run: echo ${{ github.event.action }}
      - uses: actions/checkout@v2
        if: github.event.action == 'merged'
      - name: step01
        if: github.event.action == 'merged'
        run: |
          echo test123
          yarn env
          echo ${{ secrets.SOME_SECRET }}
 
# some change 3
